In [12]:
import numpy as np
a = np.random.rand(5,2,2)
print(a)
print("sa as")
print(a.reshape(5,-1).T)


[[[0.56860035 0.0033126 ]
  [0.36554434 0.268366  ]]

 [[0.23043752 0.18216227]
  [0.50250389 0.62397307]]

 [[0.89542663 0.25454187]
  [0.82743715 0.07266013]]

 [[0.13618932 0.22490452]
  [0.33232959 0.22540264]]

 [[0.59845899 0.07565888]
  [0.28535379 0.27098913]]]
sa as
[[0.56860035 0.23043752 0.89542663 0.13618932 0.59845899]
 [0.0033126  0.18216227 0.25454187 0.22490452 0.07565888]
 [0.36554434 0.50250389 0.82743715 0.33232959 0.28535379]
 [0.268366   0.62397307 0.07266013 0.22540264 0.27098913]]


In [2]:
w = 4
db = 53
params = {"w":w,"db":db}
print(params["db"])

53
